language: perl
matrix:
 include:
  - perl: "5.18"
    env: USE_SYSTEM_PERL=1
  - perl: "5.26"
  - perl: "5.22"
  - perl: "5.20"
  - perl: "5.18"
  - perl: "5.18"
    env: RUN_XVFB=no
  - perl: "5.16"
  - perl: "5.14"
  - perl: "5.12"
  - perl: "5.10"
  - perl: "5.8"

before_install:
 - if [ "$USE_SYSTEM_PERL" = 1 ]; then perlbrew off; fi
 - sudo apt-get update -qq
 - PKG_LIST=
 - if [ "$USE_SYSTEM_PERL"  = 1    ]; then PKG_LIST+=" perl-tk";                                fi
 - if [ "$USE_SYSTEM_PERL" != 1    ]; then PKG_LIST+=" libx11-dev libfreetype6-dev libxft-dev"; fi
 - if [ "$RUN_XVFB"        != "no" ]; then PKG_LIST+=" xvfb twm";                               fi
 - sudo apt-get install -qq $PKG_LIST
 - if [ "$RUN_XVFB" = "no" ] ; then echo no X11 server; else Xvfb :123 & export DISPLAY=:123; fi
 - if [ "$RUN_XVFB" = "no" ] ; then echo no X11 server; else perl -MTime::HiRes=sleep -e '$until = time+10; while(time <= $until) { -e "/tmp/.X11-unix/X123" and exit 0; sleep 0.1 } exit 1'; fi
 - if [ "$RUN_XVFB" = "no" ] ; then echo no X11 server; else twm & fi
 - export HARNESS_OPTIONS=j4:c HARNESS_TIMER=1

branches:
 except:
  - /appveyor/
